# Menggunakan image node versi 16 sebagai base image
FROM node:16

# Mengatur direktori kerja di dalam container
WORKDIR /app

# Menyalin seluruh kode proyek
COPY . .

# Menginstall dependencies
RUN npm install


# Expose port yang digunakan oleh aplikasi Express.js
EXPOSE 4000

CMD npm run start 